name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install automake argp-standalone googletest
          elif [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update && sudo apt install -y libgtest-dev
          fi
      - name: Autoreconf
        run: autoreconf -i
      - name: Configure
        run: ./configure
      - name: Make
        run: make
      - name: Run tests
        run: make check
      - name: Upload test log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test_log_${{ matrix.os }}
          path: |
            test/test-suite.log
            config.log
