name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            brew install automake argp-standalone googletest google-benchmark
          elif [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update && sudo apt install -y libgtest-dev libbenchmark-dev
          fi
          pip3 install gcovr
      - name: Autoreconf
        run: autoreconf -i
      - name: Configure
        run: ./configure --enable-gcovr
      - name: Make
        run: make
      - name: Run tests
        run: make check
      - name: Upload test log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test_log_${{ matrix.os }}
          path: |
            benchmark/*.log
            test/*.log
            test/coverage/
            config.log
